### ISSUE TITLE
Importing a plan again automatically overwrites it

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#26] opened 2022-03-27 21:00 UTC
Steps to reproduce:

1. Create a plan and send it by Email
2. Change the plan
3. Open the plan from the Email
4. Instead of asking (replace/duplicate), it would immediately overwrite it.

https://user-images.githubusercontent.com/7668264/160300809-327b3d28-b79f-44d2-ad3f-162e74dcba7d.mp4

Reported by Ziv

**Comment by Albyzai** [comment] 2022-03-30 21:03
I am unsure about the intended behaviour? When doing it on iOS it seems to either overwrite it or do nothing? No dialog appears.

Anyway, dialog made in https://github.com/overlevelsesguiden/The10H-Android/commit/cef739a3337f9633302011444a2234dc802e7bb8 lmk if this is not the intended way

**Comment by Marzhel** [comment] 2022-04-03 13:34
On iOS it will show the following dialog if you try to import one with same same identifier where the updatedAt is newer than the one already in the app. If It already exists and the updatedAt is the same, it will just navigate to the existing plan

![IMG_5C9F80107577-1](https://user-images.githubusercontent.com/7668264/161430557-41c4f5cb-fc91-4c99-92b0-6d41270989d1.jpeg)

**Comment by Marzhel** [comment] 2022-04-03 13:54
I think your current solution looks fine, so unless it would be a quick change to make like iOS, I think you can just leave it as is and close this issue

**Comment by Albyzai** [comment] 2022-04-05 10:06
The dialog should display properly now, and allow for both copying and overwriting. Fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/07528976380a92f1cbb8b92ea689f00b727427b5

**Closed by Albyzai** 2022-04-05 10:06 UTC
Labels: bug
